version: '3.7'

services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - db
  db:
    build: ./services/database
    environment:
      - DATABASE=${DB_NAME}
      - USER_DB=${DB_USER}
      - PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database:
