"""rename relationship tables

Revision ID: 00a8b3edb5d1
Revises: 31f681aaf673
Create Date: 2020-05-09 23:00:26.313379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00a8b3edb5d1'
down_revision = '31f681aaf673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_promoters',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('promoter_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['promoter_id'], ['promoter.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'promoter_id')
    )
    op.create_table('promoter_users',
    sa.Column('promoter_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['promoter_id'], ['promoter.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('promoter_id', 'user_id')
    )
    op.drop_table('promoters')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('promoter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['promoter_id'], ['promoter.id'], name='users_promoter_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='users_user_id_fkey'),
    sa.PrimaryKeyConstraint('promoter_id', 'user_id', name='users_pkey')
    )
    op.create_table('promoters',
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('promoter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='promoters_event_id_fkey'),
    sa.ForeignKeyConstraint(['promoter_id'], ['promoter.id'], name='promoters_promoter_id_fkey'),
    sa.PrimaryKeyConstraint('event_id', 'promoter_id', name='promoters_pkey')
    )
    op.drop_table('promoter_users')
    op.drop_table('event_promoters')
    # ### end Alembic commands ###
