"""email verification

Revision ID: 030b84f4aa43
Revises: 67ee2d257436
Create Date: 2020-07-23 05:00:26.770976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030b84f4aa43'
down_revision = '67ee2d257436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_update', sa.Column('tag', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('emai_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'emai_verified')
    op.drop_column('event_update', 'tag')
    # ### end Alembic commands ###
