"""first association models

Revision ID: 2455d3f395dc
Revises: 00a8b3edb5d1
Create Date: 2020-05-11 03:03:32.645279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2455d3f395dc'
down_revision = '00a8b3edb5d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_promoters')
    op.add_column('event', sa.Column('profit', sa.Boolean(), nullable=False))
    op.add_column('promoter', sa.Column('username', sa.String(length=30), nullable=False))
    op.create_index(op.f('ix_promoter_username'), 'promoter', ['username'], unique=True)
    op.drop_constraint('promoter_email_key', 'promoter', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('promoter_email_key', 'promoter', ['email'])
    op.drop_index(op.f('ix_promoter_username'), table_name='promoter')
    op.drop_column('promoter', 'username')
    op.drop_column('event', 'profit')
    op.create_table('event_promoters',
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('promoter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='event_promoters_event_id_fkey'),
    sa.ForeignKeyConstraint(['promoter_id'], ['promoter.id'], name='event_promoters_promoter_id_fkey'),
    sa.PrimaryKeyConstraint('event_id', 'promoter_id', name='event_promoters_pkey')
    )
    # ### end Alembic commands ###
