"""empty message

Revision ID: 67ee2d257436
Revises: 71f9318458e5
Create Date: 2020-07-18 23:38:03.571467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67ee2d257436'
down_revision = '71f9318458e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_update', sa.Column('text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_update', 'text')
    # ### end Alembic commands ###
