"""empty message

Revision ID: 970f7415efce
Revises: 9b4c9429bf97
Create Date: 2020-07-13 03:50:02.419104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '970f7415efce'
down_revision = '9b4c9429bf97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_promoter', sa.Column('status', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_promoter', 'status')
    # ### end Alembic commands ###
