"""empty message

Revision ID: b4c25427c875
Revises: 9a5ada577106
Create Date: 2020-07-24 04:59:02.616978

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import column, table

from project.apps.event.models.eventUpdate import EventUpdate

# revision identifiers, used by Alembic.
revision = 'b4c25427c875'
down_revision = '9a5ada577106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    event_update = table('event_update', column('tag'))
    op.execute(event_update.update().values(tag=EventUpdate.Tag.GENERAL.value))
    
    op.alter_column('event_update', 'tag',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_update', 'tag',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
