"""create association models

Revision ID: e58913d0087e
Revises: 2455d3f395dc
Create Date: 2020-05-11 03:09:03.224027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e58913d0087e'
down_revision = '2455d3f395dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_promoter',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('promoter_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['promoter_id'], ['promoter.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'promoter_id')
    )
    op.create_table('promoter_user',
    sa.Column('promoter_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['promoter_id'], ['promoter.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('promoter_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promoter_user')
    op.drop_table('event_promoter')
    # ### end Alembic commands ###
